import { User, Employee } from '@/types';

// Mock users with system-generated login IDs
export const MOCK_USERS: User[] = [
  {
    id: '1',
    loginId: 'ADM001',
    role: 'ADMIN',
    name: 'Admin User',
    email: 'admin@dayflow.com',
  },
  {
    id: '2',
    loginId: 'HR001',
    role: 'HR',
    name: 'HR Manager',
    email: 'hr@dayflow.com',
  },
  {
    id: '3',
    loginId: 'EMP001',
    role: 'EMPLOYEE',
    name: 'John Doe',
    email: 'john.doe@dayflow.com',
  },
];

// Mock employees data
export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: '1',
    employeeId: 'EMP001',
    name: 'John Doe',
    email: 'john.doe@dayflow.com',
    department: 'Engineering',
    position: 'Senior Developer',
    joinDate: '2023-01-15',
    salary: 120000,
    status: 'ACTIVE',
    attendanceStatus: 'present',
    manager: 'Jane Smith',
    phone: '+1-555-0101',
  },
  {
    id: '2',
    employeeId: 'EMP002',
    name: 'Jane Smith',
    email: 'jane.smith@dayflow.com',
    department: 'Engineering',
    position: 'Engineering Manager',
    joinDate: '2022-06-01',
    salary: 150000,
    status: 'ACTIVE',
    attendanceStatus: 'present',
    phone: '+1-555-0102',
  },
  {
    id: '3',
    employeeId: 'EMP003',
    name: 'Alice Johnson',
    email: 'alice.johnson@dayflow.com',
    department: 'HR',
    position: 'HR Manager',
    joinDate: '2022-03-10',
    salary: 110000,
    status: 'ACTIVE',
    attendanceStatus: 'on-leave',
    phone: '+1-555-0103',
  },
  {
    id: '4',
    employeeId: 'EMP004',
    name: 'Bob Williams',
    email: 'bob.williams@dayflow.com',
    department: 'Sales',
    position: 'Sales Executive',
    joinDate: '2023-05-20',
    salary: 95000,
    status: 'ACTIVE',
    attendanceStatus: 'absent',
    manager: 'Carol Brown',
    phone: '+1-555-0104',
  },
  {
    id: '5',
    employeeId: 'EMP005',
    name: 'Carol Brown',
    email: 'carol.brown@dayflow.com',
    department: 'Sales',
    position: 'Sales Manager',
    joinDate: '2021-11-15',
    salary: 130000,
    status: 'ACTIVE',
    attendanceStatus: 'present',
    phone: '+1-555-0105',
  },
  {
    id: '6',
    employeeId: 'EMP006',
    name: 'David Lee',
    email: 'david.lee@dayflow.com',
    department: 'Marketing',
    position: 'Marketing Specialist',
    joinDate: '2023-08-01',
    salary: 85000,
    status: 'ACTIVE',
    attendanceStatus: 'present',
    manager: 'Eva Davis',
    phone: '+1-555-0106',
  },
  {
    id: '7',
    employeeId: 'EMP007',
    name: 'Eva Davis',
    email: 'eva.davis@dayflow.com',
    department: 'Marketing',
    position: 'Marketing Manager',
    joinDate: '2022-09-12',
    salary: 125000,
    status: 'ACTIVE',
    attendanceStatus: 'on-leave',
    phone: '+1-555-0107',
  },
  {
    id: '8',
    employeeId: 'EMP008',
    name: 'Frank Miller',
    email: 'frank.miller@dayflow.com',
    department: 'Engineering',
    position: 'Junior Developer',
    joinDate: '2024-01-10',
    salary: 75000,
    status: 'ACTIVE',
    attendanceStatus: 'absent',
    manager: 'Jane Smith',
    phone: '+1-555-0108',
  },
];

export const COLORS = {
  primary: {
    50: '#f5f3ff',
    100: '#ede9fe',
    200: '#ddd6fe',
    300: '#c4b5fd',
    400: '#a78bfa',
    500: '#8b5cf6',
    600: '#7c3aed',
    700: '#6d28d9',
    800: '#5b21b6',
    900: '#4c1d95',
  },
  indigo: {
    50: '#eef2ff',
    100: '#e0e7ff',
    200: '#c7d2fe',
    300: '#a5b4fc',
    400: '#818cf8',
    500: '#6366f1',
    600: '#4f46e5',
    700: '#4338ca',
    800: '#3730a3',
    900: '#312e81',
  },
  dark: {
    bg: '#0f0f23',
    surface: '#1a1a3e',
    surfaceHover: '#252550',
    border: '#2d2d5f',
    text: '#e5e7eb',
    textSecondary: '#9ca3af',
  },
};

