import { TimeOffRequest } from '@/types';

// Mock time-off requests
export const MOCK_TIME_OFF_REQUESTS: TimeOffRequest[] = [
  {
    id: '1',
    employeeId: 'EMP001',
    employeeName: 'John Doe',
    leaveType: 'vacation',
    startDate: '2024-12-20',
    endDate: '2024-12-27',
    days: 5,
    reason: 'Family vacation',
    status: 'pending',
    submittedDate: '2024-12-10',
  },
  {
    id: '2',
    employeeId: 'EMP002',
    employeeName: 'Jane Smith',
    leaveType: 'sick',
    startDate: '2024-12-15',
    endDate: '2024-12-16',
    days: 2,
    reason: 'Medical appointment',
    status: 'approved',
    submittedDate: '2024-12-12',
    reviewedBy: 'Admin User',
    reviewedDate: '2024-12-13',
  },
  {
    id: '3',
    employeeId: 'EMP003',
    employeeName: 'Alice Johnson',
    leaveType: 'personal',
    startDate: '2024-12-18',
    endDate: '2024-12-18',
    days: 1,
    reason: 'Personal matters',
    status: 'rejected',
    submittedDate: '2024-12-11',
    reviewedBy: 'HR Manager',
    reviewedDate: '2024-12-12',
  },
  {
    id: '4',
    employeeId: 'EMP004',
    employeeName: 'Bob Williams',
    leaveType: 'vacation',
    startDate: '2024-12-25',
    endDate: '2024-12-31',
    days: 5,
    reason: 'Holiday break',
    status: 'pending',
    submittedDate: '2024-12-08',
  },
  {
    id: '5',
    employeeId: 'EMP005',
    employeeName: 'Carol Brown',
    leaveType: 'sick',
    startDate: '2024-12-14',
    endDate: '2024-12-14',
    days: 1,
    reason: 'Sick leave',
    status: 'approved',
    submittedDate: '2024-12-13',
    reviewedBy: 'Admin User',
    reviewedDate: '2024-12-13',
  },
];

export const LEAVE_TYPES = {
  vacation: { label: 'Vacation', icon: '🏖️' },
  sick: { label: 'Sick Leave', icon: '🏥' },
  personal: { label: 'Personal', icon: '📅' },
  other: { label: 'Other', icon: '📝' },
};

